wd: /data/exploratory/Users/jeff.alvarez/omics-pipeline
fastqs: data/samples
ID: 2020_04_30_test
Title: "2020-04-30 Test"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
wd: /data/exploratory/Users/jeff.alvarez/omics-pipeline
fastqs: /data/exploratory/Users/jeff.alvarez/omics-pipeline/data/samples
samples:
        untreated: /data/exploratory/Users/jeff.alvarez/omics-pipeline/data/samples/untreated_1.fq.gz
        dex: /data/exploratory/Users/jeff.alvarez/omics-pipeline/data/samples/dex_1.fq.gz
        alb: /data/exploratory/Users/jeff.alvarez/omics-pipeline/data/samples/alb_1.fq.gz
        alb_dex: /data/exploratory/Users/jeff.alvarez/omics-pipeline/data/samples/alb_dex_1.fq.gz
ref:
        fa: /data/exploratory/Users/jeff.alvarez/omics-pipeline/data/Human_B37.3_chr1.fasta
        gtf: /data/exploratory/Users/jeff.alvarez/omics-pipeline/data/Human_B37.3_chr1.gtf
        build: Human_B37.3
